### ISSUE TITLE
【依頼】フリマアプリの挙動確認

### ISSUE THREAD

**Issue by saku1219** [saku1219/furima-29243#9]
## URL
https://furima-29243.herokuapp.com/

## Basic認証のIDとパスワード
ID : admin
pass : 1234

## 出品者用のメールアドレスとパスワード
email : test@test
pass : asdf1234

## 購入者用のメールアドレスとパスワード
email : test2@test
pass : asdf1234

## 購入用カードの番号・期限・セキュリティコード
番号 : 4242424242424242
期限 : 登録時より未来
cvc : 123

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
